### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by tormento** [pinterf/amDCT#2]
The script

```
SetMemoryMax()
SetCacheMode(0)
SetFilterMTMode("DEFAULT_MT_MODE", 2)
LoadPlugin("D:\Eseguibili\Media\DGDecNV\DGDecodeNV.dll")
DGSource("M:\In\Monster ~BDGE\1-1-01.dgi",ct=0,cb=0,cl=240,cr=240)
z_ConvertFormat(resample_filter="spline64", pixel_type="yuv420p16")
Resize8(720,540, kernel="z_Spline36Resize", noring=true, noring_c=true, fullc=true)
z_ConvertFormat(resample_filter="spline64",dither_type="error_diffusion",pixel_type="YUV420P16")
fmtc_bitdepth (bits=8,dmode=8)
amDCT(adapt=31,shift=5,quality=4,quant=9,matrix=8,expand=16,sharpWpos=6,sharpTpos=7,sharpWAmt=24,sharpTAmt=31,brightStart=205,brightAmt=30)
Prefetch(2,6)
```

gives me the error

`amDCT: out of memory`

**Comment by pinterf** [comment]
Thanks for the report, I'm refactoring the code right now, the memory allocation and deallocation is quite a mess (I did not dare to touch it yet), so everything is possible :). I'm still not quite sure that this plugin behaves nicely when multithreaded but I'm gonna be able to tell it in a week.

**Comment by pinterf** [comment]
The real error: 540 is not mod 8 height. :) No memory problems at all.
Other comments: empty SetMemoryMax has no point, it would return the actual value, if there is a variable on the left side.
SetFilterMTMode("DEFAULT_MT_MODE", 2) is also pointless, since it is the default in Avisynth+ (MT_MULTI_INSTANCE is 2)
